export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const NO_EXECUTE_PERMISSION = 'NO_EXECUTE_PERMISSION';
export const PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED';
export const FOLLOW_IDS_IS_REQUIRED = 'FOLLOW_IDS_IS_REQUIRED';
export const USERNAME_OR_PASSWORD_INCORRECT = 'USERNAME_OR_PASSWORD_INCORRECT';
